### ISSUE TITLE
Cant Create CS 

### ISSUE THREAD

**Issue by smartinez290** [usnistgov/hl7-igamt#858] opened 2020-03-24 18:49 UTC
@HossamT I am not able to create this CS because the declaration is not available "Shall be one of the codes listed in V/S.."
IZ-31: If RXA-20 (Completion Status) is valued and the value of RXA-20 (Completion Status) is one of List Values: 'CP','PA' then the value of RXA-9.1 (Identifier) **SHALL be one of codes listed in the Value Set: NIP001.**

**Comment by smartinez290** [comment] 2020-03-25 13:41
@HossamT I just realized that I can use this declaration:
![image](https://user-images.githubusercontent.com/14842422/77542573-c5196f80-6e7c-11ea-985b-ea1842f7a099.png)

**Comment by smartinez290** [comment] 2020-03-25 13:43
@HossamT never mind, the issue is still outstanding... in this declaration I need to enter a value.

**Comment by smartinez290** [comment] 2020-03-30 18:49
@carolinerosin the IG is the published IG:  CDC 2.5.1 Immunization Profile Z22

**Comment by HossamT** [comment] 2020-08-05 16:44
Closed, duplicate of #1012

**Closed by HossamT** 2020-08-05 16:44 UTC
Labels: IG-QI, bug
